server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8001}

data:
  local_data_folder: local_data/private_gpt

ui:
  enabled: true
  path: /

llm:
  mode: mock

local:
  llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.1-GGUF
  llm_hf_model_file: mistral-7b-instruct-v0.1.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5

sagemaker:
  endpoint_name: huggingface-pytorch-tgi-inference-2023-09-25-19-53-32-140

openai:
  api_key: ${OPENAI_API_KEY:}
