server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8080}

llm:
  mode: local

local:
  llm_hf_repo_id: TheBloke/Mistral-7B-Instruct-v0.1-GGUF
  llm_hf_model_file: mistral-7b-instruct-v0.1.Q4_K_M.gguf
  embedding_hf_model_name: BAAI/bge-small-en-v1.5

ui:
  enabled: true
  path: /